package com.francescobonizzi.invoiceEstimateReceiptMaker.domain

data class AppConfigurationPayments(
    var showPayPalEmail: Boolean = false,
    var payPalEmail: String? = null,
    var bankDetails: String? = null,
    var checkHolder: String? = null,
    var paymentNotes: String? = null,
    var vatPercentage: Double? = null,
    var vatLabel: String? = null,
    var isVATEnabled: Boolean = false,
    var applyDiscount: Boolean = false,
    var discountPercentage: Double? = null,
    var defaultInvoicesNotes: String? = null,
    var defaultEstimatesNotes: String? = null,
    var invoicePrefix: String? = null,
    var estimatePrefix: String? = null,
    var invoiceIdentityNumber: Int = 1,
    var estimateIdentityNumber: Int = 1,
    var invoiceUserDefinedLastId: Int = 1,
    var estimateUserDefinedLastId: Int = 1,
    var showInvoiceCode: Boolean = true,
    var showEstimateCode: Boolean = true,
    var showPaymentNotes: Boolean = false,
    var showBankTransferDetails: Boolean = false,
    var showInvoiceCreationDate: Boolean = true,
    var showInvoiceExpirationDate: Boolean = true,
    var showEstimateCreationDate: Boolean = true,
    var showEstimateExpirationDate: Boolean = true,
    var showInvoiceNotes: Boolean = false,
    var showEstimateNotes: Boolean = false,
    var defaultInvoiceExpirationDays: Int? = 30,
    var defaultEstimateExpirationDays: Int? = 30,
    var showCash: Boolean = false,
    var showCreditCard: Boolean = false,
    var showDebitCard: Boolean = false
)